### ISSUE TITLE
Review if the non-explicit Logic constructor can be narrowed to boolean

### ISSUE THREAD

**Issue by hostilefork** [metaeducation/ren-cpp#24]
I hit a bug from the boolean conversion of a `char *` string literal counting as a valid implicit `ren::Logic`.  I started thinking about how to write a constructor which would implicitly only accept a real bool, but would explicitly convert anything that could be a bool.  I tried something along these lines:

```
template <
    typename T,
    typename = typename std::enable_if<
        std::is_same<bool, T>::value, T
    >::type
>
Logic (T const & b) :
    Value (b)
{
}

// If you're super sure, use this explicit constructor
template <
    typename T,
    typename = typename std::enable_if<
        not std::is_same<bool, T>::value, T
    >::type
>
explicit Logic(T const & b) :
    Value (b)
{
}
```

It didn't work.  Don't want to get sidetracked with an SO question formalism ATM, but recording the issue here... perhaps @Morwenn has tried something like this before?  Looking for:

```
void foo(Logic const & val) {
    // ...
}

foo(true); // should work
foo("hello"); // shouldn't work
foo(15); // shouldn't work

foo(Logic {true}); // should work
foo(Logic {"hello"}); // should work
foo(Logic {15}); // should work
```

**Comment by hostilefork** [comment]
More on the subject:

http://stackoverflow.com/questions/4111495/

Having had yet another one of these bugs bite me, the conversion had to go.  Fool me twice, etc.  I don't know what the right way to do it is to give a meaningful error.  So I did the lame thing and made an undefined template function that takes any `T * const`, so you get a link time error; which is better than letting it slide.

Leaving open to discussion of better options.

**Comment by Morwenn** [comment]
This should sum up the fix pretty well:

```
struct safe_bool
{
    bool value;

    explicit safe_bool(bool value): value(value) {}

    explicit operator bool() const { return value; }

    template<typename T>
    safe_bool(T) = delete;
};

struct Logic
{
    explicit Logic(bool) {}

    template<typename T>
    Logic(const T& val): Logic(bool(safe_bool(val))) {}
};
```

Note for the future: currently, the `safe_bool` stuff is designed to only allow implicit conversions from `bool` and outrightly excludes `bool` proxies (there are some all around the existing projects, `std::integral_constant<bool, ...>` might be considered to be one of them one). Therefore, if the probem arises at some point, it might be interesting to provide a user-specializable traits to check whether a type is a `bool` proxy (_e.g_ `is_bool_proxy`) and let `safe_bool` be constructible from any type `T` satisfying `is_bool_proxy<T>::value`.

**Comment by hostilefork** [comment]
I had a strange problem when I tried substituting it in for the bool here:

https://github.com/hostilefork/rencpp/blob/develop/include/rencpp/values.hpp#L359

It seemed to think that this introduced an ambiguous constructor with the unset_t one:

https://github.com/hostilefork/rencpp/blob/develop/include/rencpp/values.hpp#L314

I don't see how those two would be ambiguous.  :-/  Do you get the same error?

**Comment by hostilefork** [comment]
Well these two original cases I listed and said "should work" here don't work, but...

```
foo(Logic {"hello"}); // should work
foo(Logic {15}); // should work
```

...there's no way to have both an implicit and explicit constructor from the same type.  So if the price of narrowing it to stop the accidents is that people have to write:

```
foo(Logic {static_cast<bool>("hello")});
foo(Logic {static_cast<bool>(15)});
```

Then the safety is the side of the fence I'm in favor of.  Closing this now.  Thanks @Morwenn!

**Comment by Morwenn** [comment]
How come they don't work? Back to the simplified test case in Coliru, it seemed like it worked like a charm: http://coliru.stacked-crooked.com/a/5452b785a806a5e0

The only errors in this example are those from the test cases that shouldn't work. Is there something more complicated going on?

**Comment by hostilefork** [comment]
_(Hey @Morwenn, hope things are going well... stop by chat and say hi when you've the time to tell the stories.)_

So... I was going and cleaning up some other project I've got (trying to incorporate some of our lessons here with CMake, Catch, and all.  And I was looking at some extra constructor parameters for SFINAE.

I thought _"ah, this will be much easier to read the function's actual interface if I just do the trick where I put the `typename = typename std::enable_if<...>` in the template spec."_

Then I recompiled and got errors, and realized what the enablements were for in the first place.  They were to change the conditions under which various constructors were explicit vs. implicit.  But once the SFINAE conditions were lifted into the template spec, they had matching signatures.  This trumped any later SFINAE that would show they had opposite conditions, and were thus never in conflict.

Seeing that my earlier code doing this had worked, I realized that must have been the problem with the booleans...I'd gotten too addicted to the cleaner form... :-)  Putting the conditions in as parameters did the trick by keeping the compiler from having a fit about the identical signatures.  Interestingly, it achieves the original specification.

The question would be "is it better?"  The main thing I was trying to protect against was someone passing a string parameter where a logic was expected on accident, and thus be more like Rebol's function-call-rules.  One might ask if you're going to disagree in general places that C++ takes a `bool` if one should use `safe_bool` everywhere?  :-/

Anyway, wanted to mention it either way...because it's an interesting point of when you can't use the template spec trick, apparently!

**Comment by Morwenn** [comment]
_(Sorry for not being there anymore. I only have internet at work or when I come back home during weekends, and I generally have many things to do when I come back home during weekends. It will probably be a bit better in a few weeks if I manage get some decent internet connexion.)_

C++, just like C, does too many implicit type conversions, so I liked your idea to have the implicit conversions fro some types but not for all, and it especially made sense for another logic type. Frankly, it would be much simpler if most of the built-in types had `explicit` conversions to whatever, and not implicit ones.

The template spec trick is the cleaner approach, but not the one that works the best. I [already encountered problems](http://stackoverflow.com/q/15427667/1364752) a while ago by always wanting to put the SFINAE trick in the template parameter. My guideline now is "put it in the template parameter if you can, otherwise in the return type, otherwise in the parameters". I wouldn't be surprised if it had something to do with [dependent names](http://en.cppreference.com/w/cpp/language/dependent_name) but that's something that I never fully managed to wrap my mind around...

Now, to the question "which is better?", I can't really tell. I find the name `safe_bool` good enough for self-documentation, but it does require to write some more code. I would say that you should take a `safe_bool` only when it is not clear what might happen with a bare `bool` (like when the user expects something and something else happens) but yet again I don't have enough experience with the idiom (is it really an idiom?) to begin with :/

**Comment by hostilefork** [comment]
So...after "meditating" a bit (and messing with Doxygen and a rabble of other things)...I came back to this.  I think the toss-up here leans toward _"try not to reinvent C++ base types in the interfaces if you can help it"_.

If one were to jump into fixing stuff one could use something like the [SafeInt](https://msdn.microsoft.com/en-us/library/dd570023.aspx) library instead of an integer.  _(Which in my pathological application framework I actually did consider using, even though it wasn't cryptographic or security-related.)_

I think erring on the side of not reinventing type signatures from what people are used to--if the bugs I wanted to avoid can be caught another way--is best here.  Because taken to extreme this suggests not using bools anywhere; which may be a great idea but in making an impression one must "choose one's battles."

Still, now we know.  So, thanks!  :-)

**Comment by Morwenn** [comment]
It's great to see that you finally found a solution with SFINAE instead of esoteric tricks. While `std::is_convertible` is not pretty, it is actually exactly the tool we need and documents well the issue by itself. Congratulations :)
